// sync-schema.mjs
//
// Imports the canonical MBS Planner schema snapshot (web/scripts/pb-schema.json) into a
// PocketBase instance — used to provision hosted instances (e.g. PocketHost) whose schema
// cannot come from backend/pb_migrations/ (that directory is not self-bootstrapping: the
// base collections have no `created_*` migrations and some migrations reference the
// developer's local database).
//
// The snapshot was generated by bootstrap-schema.mjs against a fresh PocketBase and exported
// via GET /api/collections (system collections excluded). It contains the 27 business
// collections in their FINAL state (see DATA_DICTIONARY.md) with resolved relation ids.
//
// Usage:
//   PB_URL=https://<instance>.pockethost.io PB_ADMIN_EMAIL=... PB_ADMIN_PASSWORD=... \
//     node web/scripts/sync-schema.mjs
//
// Idempotent: existing collections are merged in place (deleteMissing=false keeps anything
// else that may already exist on the target).

import PocketBase from "pocketbase";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PB_URL, getAdminCreds } from "./creds.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const schemaPath = path.resolve(__dirname, "pb-schema.json");

const pb = new PocketBase(PB_URL);
const { email, password } = getAdminCreds();
await pb.collection("_superusers").authWithPassword(email, password);

const collections = JSON.parse(fs.readFileSync(schemaPath, "utf8"));
console.log(`Target: ${PB_URL}`);
console.log(`Importing ${collections.length} collections from ${schemaPath}...`);

try {
  await pb.collections.import(collections, false);
  console.log("✅ Schema imported successfully.");
} catch (err) {
  console.error("Import failed:", JSON.stringify(err?.data?.data || err?.data || err?.message || err));
  process.exit(1);
}
