/// <reference path="../pb_data/types.d.ts" />
// GENERATED by web/scripts/gen-created-migrations.mjs — do not edit by hand.
//
// The `users` auth collection is auto-created by PocketBase on fresh boot with
// only the default fields. The custom fields (department_id, role_id, ...) were
// historically added in the admin UI, never via migration, so a fresh instance
// came up without them and every role-based API rule silently failed. This sync
// adds whatever custom fields are missing (idempotent — existing deployments
// already have them) and pins the final rules.
migrate((app) => {
  const collection = app.findCollectionByNameOrId("_pb_users_auth_")

  const names = collection.fields.fieldNames()
  for (const f of [{"hidden":false,"id":"autodate2990389176","name":"created","onCreate":true,"onUpdate":false,"presentable":false,"system":false,"type":"autodate"},{"hidden":false,"id":"autodate3332085495","name":"updated","onCreate":true,"onUpdate":true,"presentable":false,"system":false,"type":"autodate"},{"cascadeDelete":false,"collectionId":"pbc_3865025440","help":"","hidden":false,"id":"rel_users_dept","maxSelect":1,"minSelect":0,"name":"department_id","presentable":false,"required":false,"system":false,"type":"relation"},{"cascadeDelete":false,"collectionId":"pbc_2105053228","help":"","hidden":false,"id":"rel_users_role","maxSelect":1,"minSelect":0,"name":"role_id","presentable":false,"required":false,"system":false,"type":"relation"},{"help":"","hidden":false,"id":"num_users_reminder","max":null,"min":null,"name":"reminder_days","onlyInt":false,"presentable":false,"required":false,"system":false,"type":"number"},{"help":"","hidden":false,"id":"bool_users_disabled","name":"disabled","presentable":false,"required":false,"system":false,"type":"bool"}]) {
    if (!names.includes(f.name)) {
      collection.fields.add(new Field(f))
    }
  }

  unmarshal({
  "listRule": "@request.auth.id != \"\"",
  "viewRule": "@request.auth.id != \"\"",
  "createRule": "@request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\"",
  "updateRule": "@request.auth.id = id || @request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\"",
  "deleteRule": "id = @request.auth.id"
}, collection)

  return app.save(collection)
}, (app) => {
  // best-effort revert: remove the custom fields we may have added
  try {
    const collection = app.findCollectionByNameOrId("_pb_users_auth_")
    for (const name of ["department_id", "role_id", "reminder_days", "disabled"]) {
      const field = collection.fields.getByName(name)
      if (field && !field.system) collection.fields.removeById(field.id)
    }
    app.save(collection)
  } catch (e) { /* ignore */ }
})
