/// <reference path="../pb_data/types.d.ts" />
// GENERATED by web/scripts/gen-created-migrations.mjs — do not edit by hand.
//
// Creates the `departments` collection in its FINAL state (from the canonical
// schema snapshot web/scripts/pb-schema.json) using the collection id that the
// historical updated_* migrations reference. Existing deployments already have
// this collection, so the up() is a no-op for them; fresh instances get the
// full schema and the updated_* migrations below simply no-op on the fields
// they would otherwise add (they are guarded to be idempotent).
migrate((app) => {
  try {
    app.findCollectionByNameOrId("departments")
    // already exists (pre-existing deployment) — nothing to do
    return
  } catch (e) {
    // not found — create below
  }

  const collection = new Collection({
  "id": "pbc_3865025440",
  "listRule": "@request.auth.id != \"\"",
  "viewRule": "@request.auth.id != \"\"",
  "createRule": "@request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\"",
  "updateRule": "@request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\"",
  "deleteRule": "@request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\"",
  "name": "departments",
  "type": "base",
  "fields": [
    {
      "autogeneratePattern": "[a-z0-9]{15}",
      "help": "",
      "hidden": false,
      "id": "text3208210256",
      "max": 15,
      "min": 15,
      "name": "id",
      "pattern": "^[a-z0-9]+$",
      "presentable": false,
      "primaryKey": true,
      "required": true,
      "system": true,
      "type": "text"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "text_dep_code",
      "max": 0,
      "min": 0,
      "name": "code",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": true,
      "system": false,
      "type": "text"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "text_dep_name",
      "max": 0,
      "min": 0,
      "name": "name",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": true,
      "system": false,
      "type": "text"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_dep_counted",
      "name": "is_counted",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "help": "",
      "hidden": false,
      "id": "rel_dep_leader",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "leader_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "hidden": false,
      "id": "autodate2990389176",
      "name": "created",
      "onCreate": true,
      "onUpdate": false,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "hidden": false,
      "id": "autodate3332085495",
      "name": "updated",
      "onCreate": true,
      "onUpdate": true,
      "presentable": false,
      "system": false,
      "type": "autodate"
    }
  ],
  "indexes": [],
  "created": "2026-08-17 03:26:11.707Z",
  "updated": "2026-08-17 03:26:12.004Z",
  "system": false
})

  return app.save(collection)
}, (app) => {
  try {
    const collection = app.findCollectionByNameOrId("departments")
    return app.delete(collection)
  } catch (e) {
    // nothing to delete
  }
})
