/// <reference path="../pb_data/types.d.ts" />
// GENERATED by web/scripts/gen-created-migrations.mjs — do not edit by hand.
//
// Creates the `comments` collection in its FINAL state (from the canonical
// schema snapshot web/scripts/pb-schema.json) using the collection id that the
// historical updated_* migrations reference. Existing deployments already have
// this collection, so the up() is a no-op for them; fresh instances get the
// full schema and the updated_* migrations below simply no-op on the fields
// they would otherwise add (they are guarded to be idempotent).
migrate((app) => {
  try {
    app.findCollectionByNameOrId("comments")
    // already exists (pre-existing deployment) — nothing to do
    return
  } catch (e) {
    // not found — create below
  }

  const collection = new Collection({
  "id": "pbc_533777971",
  "listRule": "@request.auth.id != \"\"",
  "viewRule": "@request.auth.id != \"\"",
  "createRule": "@request.auth.id = user_id || @request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\"",
  "updateRule": "@request.auth.id = user_id",
  "deleteRule": "@request.auth.id = user_id",
  "name": "comments",
  "type": "base",
  "fields": [
    {
      "autogeneratePattern": "[a-z0-9]{15}",
      "help": "",
      "hidden": false,
      "id": "text3208210256",
      "max": 15,
      "min": 15,
      "name": "id",
      "pattern": "^[a-z0-9]+$",
      "presentable": false,
      "primaryKey": true,
      "required": true,
      "system": true,
      "type": "text"
    },
    {
      "cascadeDelete": true,
      "collectionId": "pbc_2602490748",
      "help": "",
      "hidden": false,
      "id": "rel_comment_task",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "task_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "help": "",
      "hidden": false,
      "id": "rel_comment_user",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "user_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "text_comment_content",
      "max": 0,
      "min": 0,
      "name": "content",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": false,
      "system": false,
      "type": "text"
    },
    {
      "help": "",
      "hidden": false,
      "id": "file_comment_files",
      "maxSelect": 99,
      "maxSize": 20971520,
      "mimeTypes": [
        "image/png",
        "image/jpeg",
        "image/gif",
        "application/pdf",
        "application/msword",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "text/csv"
      ],
      "name": "files",
      "presentable": false,
      "protected": false,
      "required": false,
      "system": false,
      "thumbs": null,
      "type": "file"
    },
    {
      "hidden": false,
      "id": "autodate2990389176",
      "name": "created",
      "onCreate": true,
      "onUpdate": false,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "hidden": false,
      "id": "autodate3332085495",
      "name": "updated",
      "onCreate": true,
      "onUpdate": true,
      "presentable": false,
      "system": false,
      "type": "autodate"
    }
  ],
  "indexes": [
    "CREATE INDEX `idx_comments_task_id` ON `comments` (task_id)"
  ],
  "created": "2026-08-17 03:26:11.718Z",
  "updated": "2026-08-17 03:26:12.495Z",
  "system": false
})

  return app.save(collection)
}, (app) => {
  try {
    const collection = app.findCollectionByNameOrId("comments")
    return app.delete(collection)
  } catch (e) {
    // nothing to delete
  }
})
