/// <reference path="../pb_data/types.d.ts" />
// GENERATED by web/scripts/gen-created-migrations.mjs — do not edit by hand.
//
// Creates the `tasks` collection in its FINAL state (from the canonical
// schema snapshot web/scripts/pb-schema.json) using the collection id that the
// historical updated_* migrations reference. Existing deployments already have
// this collection, so the up() is a no-op for them; fresh instances get the
// full schema and the updated_* migrations below simply no-op on the fields
// they would otherwise add (they are guarded to be idempotent).
migrate((app) => {
  try {
    app.findCollectionByNameOrId("tasks")
    // already exists (pre-existing deployment) — nothing to do
    return
  } catch (e) {
    // not found — create below
  }

  const collection = new Collection({
  "id": "pbc_2602490748",
  "listRule": "@request.auth.id != \"\"",
  "viewRule": "@request.auth.id != \"\"",
  "createRule": "@request.auth.role_id.can_add_tasks = true || @request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\"",
  "updateRule": "@request.auth.role_id.can_edit_tasks = true || @request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\" || @request.auth.id = executor_id || @request.auth.id = supervisor_id",
  "deleteRule": "@request.auth.role_id.can_delete_tasks = true || @request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\"",
  "name": "tasks",
  "type": "base",
  "fields": [
    {
      "autogeneratePattern": "[a-z0-9]{15}",
      "help": "",
      "hidden": false,
      "id": "text3208210256",
      "max": 15,
      "min": 15,
      "name": "id",
      "pattern": "^[a-z0-9]+$",
      "presentable": false,
      "primaryKey": true,
      "required": true,
      "system": true,
      "type": "text"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "text_task_name",
      "max": 0,
      "min": 0,
      "name": "name",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": true,
      "system": false,
      "type": "text"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "text_task_desc",
      "max": 0,
      "min": 0,
      "name": "description",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": false,
      "system": false,
      "type": "text"
    },
    {
      "cascadeDelete": false,
      "collectionId": "pbc_4263585338",
      "help": "",
      "hidden": false,
      "id": "rel_task_plan",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "plan_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "help": "",
      "hidden": false,
      "id": "select_task_category",
      "maxSelect": 1,
      "name": "category",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "select",
      "values": [
        "normal",
        "sudden",
        "important"
      ]
    },
    {
      "cascadeDelete": false,
      "collectionId": "pbc_3865025440",
      "help": "",
      "hidden": false,
      "id": "rel_task_host_dept",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "host_dept_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "help": "",
      "hidden": false,
      "id": "rel_task_executor",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "executor_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "help": "",
      "hidden": false,
      "id": "rel_task_supervisor",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "supervisor_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "help": "",
      "hidden": false,
      "id": "rel_task_collabs",
      "maxSelect": 10,
      "minSelect": 0,
      "name": "collaborator_ids",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "help": "",
      "hidden": false,
      "id": "date_task_start",
      "max": "",
      "min": "",
      "name": "start_date",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "date"
    },
    {
      "help": "",
      "hidden": false,
      "id": "date_task_deadline",
      "max": "",
      "min": "",
      "name": "deadline",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "date"
    },
    {
      "help": "",
      "hidden": false,
      "id": "select_task_status",
      "maxSelect": 1,
      "name": "status",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "select",
      "values": [
        "not_started",
        "in_progress",
        "pending_approval",
        "completed",
        "proposed_extension",
        "proposed_cancellation",
        "cancelled"
      ]
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_task_recurring",
      "name": "is_recurring",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "help": "",
      "hidden": false,
      "id": "select_task_recur_type",
      "maxSelect": 1,
      "name": "recurring_type",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "select",
      "values": [
        "monthly",
        "weekly"
      ]
    },
    {
      "help": "",
      "hidden": false,
      "id": "num_task_recur_value",
      "max": null,
      "min": null,
      "name": "recurring_value",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_task_deleted",
      "name": "is_deleted",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_task_ad_hoc",
      "name": "is_ad_hoc",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "hidden": false,
      "id": "autodate2990389176",
      "name": "created",
      "onCreate": true,
      "onUpdate": false,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "hidden": false,
      "id": "autodate3332085495",
      "name": "updated",
      "onCreate": true,
      "onUpdate": true,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_task_high_impact",
      "name": "is_high_impact",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "cascadeDelete": false,
      "collectionId": "pbc_3865025440",
      "help": "",
      "hidden": false,
      "id": "rel_task_coord_dept",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "coordinating_dept_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "help": "",
      "hidden": false,
      "id": "date_task_completed",
      "max": "",
      "min": "",
      "name": "completed_at",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "date"
    },
    {
      "help": "",
      "hidden": false,
      "id": "num_task_rating",
      "max": 5,
      "min": 1,
      "name": "rating",
      "onlyInt": true,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "help": "",
      "hidden": false,
      "id": "rel_task_rated_by",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "rated_by_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "help": "",
      "hidden": false,
      "id": "date_task_rated_at",
      "max": "",
      "min": "",
      "name": "rated_at",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "date"
    }
  ],
  "indexes": [
    "CREATE INDEX `idx_tasks_deleted` ON `tasks` (is_deleted)",
    "CREATE INDEX `idx_tasks_executor_status` ON `tasks` (executor_id, status)",
    "CREATE INDEX `idx_tasks_plan_id` ON `tasks` (plan_id)",
    "CREATE INDEX `idx_tasks_deadline` ON `tasks` (deadline)",
    "CREATE INDEX `idx_tasks_host_dept` ON `tasks` (host_dept_id)",
    "CREATE INDEX `idx_tasks_completed_at` ON `tasks` (completed_at)",
    "CREATE INDEX `idx_tasks_updated` ON `tasks` (updated)"
  ],
  "created": "2026-08-17 03:26:11.715Z",
  "updated": "2026-08-17 03:26:12.585Z",
  "system": false
})

  return app.save(collection)
}, (app) => {
  try {
    const collection = app.findCollectionByNameOrId("tasks")
    return app.delete(collection)
  } catch (e) {
    // nothing to delete
  }
})
