/// <reference path="../pb_data/types.d.ts" />
// GENERATED by web/scripts/gen-created-migrations.mjs — do not edit by hand.
//
// Creates the `kpi_scores` collection in its FINAL state (from the canonical
// schema snapshot web/scripts/pb-schema.json) using the collection id that the
// historical updated_* migrations reference. Existing deployments already have
// this collection, so the up() is a no-op for them; fresh instances get the
// full schema and the updated_* migrations below simply no-op on the fields
// they would otherwise add (they are guarded to be idempotent).
migrate((app) => {
  try {
    app.findCollectionByNameOrId("kpi_scores")
    // already exists (pre-existing deployment) — nothing to do
    return
  } catch (e) {
    // not found — create below
  }

  const collection = new Collection({
  "id": "pbc_1748357255",
  "listRule": "@request.auth.id != \"\"",
  "viewRule": "@request.auth.id != \"\"",
  "createRule": null,
  "updateRule": null,
  "deleteRule": null,
  "name": "kpi_scores",
  "type": "base",
  "fields": [
    {
      "autogeneratePattern": "[a-z0-9]{15}",
      "help": "",
      "hidden": false,
      "id": "text3208210256",
      "max": 15,
      "min": 15,
      "name": "id",
      "pattern": "^[a-z0-9]+$",
      "presentable": false,
      "primaryKey": true,
      "required": true,
      "system": true,
      "type": "text"
    },
    {
      "cascadeDelete": true,
      "collectionId": "pbc_2602490748",
      "help": "",
      "hidden": false,
      "id": "rel_kpi_task",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "task_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "help": "",
      "hidden": false,
      "id": "num_kpi_base",
      "max": null,
      "min": null,
      "name": "base_score",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "help": "",
      "hidden": false,
      "id": "num_kpi_diff",
      "max": null,
      "min": null,
      "name": "difficulty_coeff",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "help": "",
      "hidden": false,
      "id": "num_kpi_progress",
      "max": null,
      "min": null,
      "name": "progress_score",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "help": "",
      "hidden": false,
      "id": "num_kpi_result",
      "max": null,
      "min": null,
      "name": "result_rating",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "help": "",
      "hidden": false,
      "id": "num_kpi_final",
      "max": null,
      "min": null,
      "name": "final_score",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "hidden": false,
      "id": "autodate2990389176",
      "name": "created",
      "onCreate": true,
      "onUpdate": false,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "hidden": false,
      "id": "autodate3332085495",
      "name": "updated",
      "onCreate": true,
      "onUpdate": true,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "help": "",
      "hidden": false,
      "id": "num_kpi_max",
      "max": null,
      "min": null,
      "name": "max_converted_score",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    }
  ],
  "indexes": [
    "CREATE INDEX `idx_kpi_task_id` ON `kpi_scores` (task_id)"
  ],
  "created": "2026-08-17 03:26:11.724Z",
  "updated": "2026-08-17 03:26:12.459Z",
  "system": false
})

  return app.save(collection)
}, (app) => {
  try {
    const collection = app.findCollectionByNameOrId("kpi_scores")
    return app.delete(collection)
  } catch (e) {
    // nothing to delete
  }
})
