/// <reference path="../pb_data/types.d.ts" />
// GENERATED by web/scripts/gen-created-migrations.mjs — do not edit by hand.
//
// Creates the `plans` collection in its FINAL state (from the canonical
// schema snapshot web/scripts/pb-schema.json) using the collection id that the
// historical updated_* migrations reference. Existing deployments already have
// this collection, so the up() is a no-op for them; fresh instances get the
// full schema and the updated_* migrations below simply no-op on the fields
// they would otherwise add (they are guarded to be idempotent).
migrate((app) => {
  try {
    app.findCollectionByNameOrId("plans")
    // already exists (pre-existing deployment) — nothing to do
    return
  } catch (e) {
    // not found — create below
  }

  const collection = new Collection({
  "id": "pbc_4263585338",
  "listRule": "@request.auth.id != \"\"",
  "viewRule": "@request.auth.id != \"\"",
  "createRule": "@request.auth.role_id.can_add_plans = true || @request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\"",
  "updateRule": "@request.auth.role_id.can_edit_plans = true || @request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\"",
  "deleteRule": "@request.auth.role_id.can_delete_plans = true || @request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\"",
  "name": "plans",
  "type": "base",
  "fields": [
    {
      "autogeneratePattern": "[a-z0-9]{15}",
      "help": "",
      "hidden": false,
      "id": "text3208210256",
      "max": 15,
      "min": 15,
      "name": "id",
      "pattern": "^[a-z0-9]+$",
      "presentable": false,
      "primaryKey": true,
      "required": true,
      "system": true,
      "type": "text"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "text_plan_name",
      "max": 0,
      "min": 0,
      "name": "name",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": true,
      "system": false,
      "type": "text"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "text_plan_desc",
      "max": 0,
      "min": 0,
      "name": "description",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": false,
      "system": false,
      "type": "text"
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "help": "",
      "hidden": false,
      "id": "rel_plan_leader",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "leader_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "cascadeDelete": false,
      "collectionId": "pbc_3865025440",
      "help": "",
      "hidden": false,
      "id": "rel_plan_host_dept",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "host_dept_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "cascadeDelete": false,
      "collectionId": "pbc_3865025440",
      "help": "",
      "hidden": false,
      "id": "rel_plan_partner_depts",
      "maxSelect": 10,
      "minSelect": 0,
      "name": "partner_dept_ids",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "help": "",
      "hidden": false,
      "id": "date_plan_start",
      "max": "",
      "min": "",
      "name": "start_date",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "date"
    },
    {
      "help": "",
      "hidden": false,
      "id": "date_plan_end",
      "max": "",
      "min": "",
      "name": "end_date",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "date"
    },
    {
      "help": "",
      "hidden": false,
      "id": "select_plan_status",
      "maxSelect": 1,
      "name": "status",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "select",
      "values": [
        "not_started",
        "in_progress",
        "completed",
        "paused",
        "cancelled"
      ]
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_plan_sudden",
      "name": "is_sudden",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_plan_high_impact",
      "name": "is_high_impact",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "help": "",
      "hidden": false,
      "id": "num_plan_progress",
      "max": null,
      "min": null,
      "name": "progress",
      "onlyInt": false,
      "presentable": false,
      "required": false,
      "system": false,
      "type": "number"
    },
    {
      "hidden": false,
      "id": "autodate2990389176",
      "name": "created",
      "onCreate": true,
      "onUpdate": false,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "hidden": false,
      "id": "autodate3332085495",
      "name": "updated",
      "onCreate": true,
      "onUpdate": true,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_plan_deleted",
      "name": "is_deleted",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    }
  ],
  "indexes": [
    "CREATE INDEX `idx_plans_deleted` ON `plans` (is_deleted)",
    "CREATE INDEX `idx_plans_host_dept` ON `plans` (host_dept_id)",
    "CREATE INDEX `idx_plans_status` ON `plans` (status)",
    "CREATE INDEX `idx_plans_leader_deleted` ON `plans` (leader_id, is_deleted)"
  ],
  "created": "2026-08-17 03:26:11.712Z",
  "updated": "2026-08-17 03:26:12.396Z",
  "system": false
})

  return app.save(collection)
}, (app) => {
  try {
    const collection = app.findCollectionByNameOrId("plans")
    return app.delete(collection)
  } catch (e) {
    // nothing to delete
  }
})
