/// <reference path="../pb_data/types.d.ts" />
// GENERATED by web/scripts/gen-created-migrations.mjs — do not edit by hand.
//
// Creates the `roles` collection in its FINAL state (from the canonical
// schema snapshot web/scripts/pb-schema.json) using the collection id that the
// historical updated_* migrations reference. Existing deployments already have
// this collection, so the up() is a no-op for them; fresh instances get the
// full schema and the updated_* migrations below simply no-op on the fields
// they would otherwise add (they are guarded to be idempotent).
migrate((app) => {
  try {
    app.findCollectionByNameOrId("roles")
    // already exists (pre-existing deployment) — nothing to do
    return
  } catch (e) {
    // not found — create below
  }

  const collection = new Collection({
  "id": "pbc_2105053228",
  "listRule": "@request.auth.id != \"\"",
  "viewRule": "@request.auth.id != \"\"",
  "createRule": "@request.auth.role_id.can_manage = true",
  "updateRule": "@request.auth.role_id.can_manage = true",
  "deleteRule": "@request.auth.role_id.can_manage = true",
  "name": "roles",
  "type": "base",
  "fields": [
    {
      "autogeneratePattern": "[a-z0-9]{15}",
      "help": "",
      "hidden": false,
      "id": "text3208210256",
      "max": 15,
      "min": 15,
      "name": "id",
      "pattern": "^[a-z0-9]+$",
      "presentable": false,
      "primaryKey": true,
      "required": true,
      "system": true,
      "type": "text"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "text_role_code",
      "max": 0,
      "min": 0,
      "name": "code",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": true,
      "system": false,
      "type": "text"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "text_role_name",
      "max": 0,
      "min": 0,
      "name": "name",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": true,
      "system": false,
      "type": "text"
    },
    {
      "help": "",
      "hidden": false,
      "id": "select_role_level",
      "maxSelect": 1,
      "name": "level",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "select",
      "values": [
        "leadership",
        "management",
        "employee"
      ]
    },
    {
      "help": "",
      "hidden": false,
      "id": "select_role_scope",
      "maxSelect": 1,
      "name": "view_scope",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "select",
      "values": [
        "all",
        "department",
        "group",
        "personal"
      ]
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_role_add_plans",
      "name": "can_add_plans",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_role_edit_plans",
      "name": "can_edit_plans",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_role_del_plans",
      "name": "can_delete_plans",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_role_add_tasks",
      "name": "can_add_tasks",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_role_edit_tasks",
      "name": "can_edit_tasks",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_role_del_tasks",
      "name": "can_delete_tasks",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_role_manage",
      "name": "can_manage",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "text_role_desc",
      "max": 0,
      "min": 0,
      "name": "description",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": false,
      "system": false,
      "type": "text"
    },
    {
      "hidden": false,
      "id": "autodate2990389176",
      "name": "created",
      "onCreate": true,
      "onUpdate": false,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "hidden": false,
      "id": "autodate3332085495",
      "name": "updated",
      "onCreate": true,
      "onUpdate": true,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_role_appr_leave",
      "name": "can_approve_leave",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    },
    {
      "help": "",
      "hidden": false,
      "id": "select_role_appr_scope",
      "maxSelect": 1,
      "name": "approval_scope",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "select",
      "values": [
        "all",
        "department",
        "group"
      ]
    },
    {
      "help": "",
      "hidden": false,
      "id": "bool_role_view_salary",
      "name": "can_view_salary",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "bool"
    }
  ],
  "indexes": [],
  "created": "2026-08-17 03:26:11.710Z",
  "updated": "2026-08-17 03:26:12.376Z",
  "system": false
})

  return app.save(collection)
}, (app) => {
  try {
    const collection = app.findCollectionByNameOrId("roles")
    return app.delete(collection)
  } catch (e) {
    // nothing to delete
  }
})
