/// <reference path="../pb_data/types.d.ts" />
// GENERATED by web/scripts/gen-created-migrations.mjs — do not edit by hand.
//
// Creates the `proposals` collection in its FINAL state (from the canonical
// schema snapshot web/scripts/pb-schema.json) using the collection id that the
// historical updated_* migrations reference. Existing deployments already have
// this collection, so the up() is a no-op for them; fresh instances get the
// full schema and the updated_* migrations below simply no-op on the fields
// they would otherwise add (they are guarded to be idempotent).
migrate((app) => {
  try {
    app.findCollectionByNameOrId("proposals")
    // already exists (pre-existing deployment) — nothing to do
    return
  } catch (e) {
    // not found — create below
  }

  const collection = new Collection({
  "id": "pbc_3247561751",
  "listRule": "@request.auth.id != \"\"",
  "viewRule": "@request.auth.id != \"\"",
  "createRule": "@request.auth.id = requester_id || @request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\"",
  "updateRule": "@request.auth.id != \"\"",
  "deleteRule": "@request.auth.role_id.can_manage = true || @request.auth.collectionName = \"_superusers\"",
  "name": "proposals",
  "type": "base",
  "fields": [
    {
      "autogeneratePattern": "[a-z0-9]{15}",
      "help": "",
      "hidden": false,
      "id": "text3208210256",
      "max": 15,
      "min": 15,
      "name": "id",
      "pattern": "^[a-z0-9]+$",
      "presentable": false,
      "primaryKey": true,
      "required": true,
      "system": true,
      "type": "text"
    },
    {
      "cascadeDelete": true,
      "collectionId": "pbc_2602490748",
      "help": "",
      "hidden": false,
      "id": "rel_prop_task",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "task_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "help": "",
      "hidden": false,
      "id": "select_prop_type",
      "maxSelect": 1,
      "name": "type",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "select",
      "values": [
        "extension",
        "cancellation"
      ]
    },
    {
      "autogeneratePattern": "",
      "help": "",
      "hidden": false,
      "id": "text_prop_reason",
      "max": 0,
      "min": 0,
      "name": "reason",
      "pattern": "",
      "presentable": false,
      "primaryKey": false,
      "required": true,
      "system": false,
      "type": "text"
    },
    {
      "help": "",
      "hidden": false,
      "id": "date_prop_new_deadline",
      "max": "",
      "min": "",
      "name": "new_deadline",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "date"
    },
    {
      "help": "",
      "hidden": false,
      "id": "select_prop_status",
      "maxSelect": 1,
      "name": "status",
      "presentable": false,
      "required": true,
      "system": false,
      "type": "select",
      "values": [
        "pending",
        "approved",
        "rejected",
        "withdrawn"
      ]
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "help": "",
      "hidden": false,
      "id": "rel_prop_requester",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "requester_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "cascadeDelete": false,
      "collectionId": "_pb_users_auth_",
      "help": "",
      "hidden": false,
      "id": "rel_prop_approver",
      "maxSelect": 1,
      "minSelect": 0,
      "name": "approver_id",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    },
    {
      "hidden": false,
      "id": "autodate2990389176",
      "name": "created",
      "onCreate": true,
      "onUpdate": false,
      "presentable": false,
      "system": false,
      "type": "autodate"
    },
    {
      "hidden": false,
      "id": "autodate3332085495",
      "name": "updated",
      "onCreate": true,
      "onUpdate": true,
      "presentable": false,
      "system": false,
      "type": "autodate"
    }
  ],
  "indexes": [
    "CREATE INDEX `idx_proposals_task_id` ON `proposals` (task_id)",
    "CREATE INDEX `idx_proposals_status` ON `proposals` (status)"
  ],
  "created": "2026-08-17 03:26:11.721Z",
  "updated": "2026-08-17 03:26:12.486Z",
  "system": false
})

  return app.save(collection)
}, (app) => {
  try {
    const collection = app.findCollectionByNameOrId("proposals")
    return app.delete(collection)
  } catch (e) {
    // nothing to delete
  }
})
