/// <reference path="../pb_data/types.d.ts" />
// GENERATED by web/scripts/gen-created-migrations.mjs — do not edit by hand.
//
// Adds `users.group_ids` (relation to professional_groups). This must run AFTER
// professional_groups exists (created at 1786900000), because PocketBase
// validates relation targets when the collection is saved. Idempotent.
migrate((app) => {
  const collection = app.findCollectionByNameOrId("_pb_users_auth_")
  if (!collection.fields.getByName("group_ids")) {
    collection.fields.add(new Field({
      "cascadeDelete": false,
      "collectionId": "pbc_professional_groups",
      "hidden": false,
      "id": "rel_users_group_ids",
      "maxSelect": 100,
      "minSelect": 0,
      "name": "group_ids",
      "presentable": false,
      "required": false,
      "system": false,
      "type": "relation"
    }))
  }
  return app.save(collection)
}, (app) => {
  try {
    const collection = app.findCollectionByNameOrId("_pb_users_auth_")
    const field = collection.fields.getByName("group_ids")
    if (field && !field.system) collection.fields.removeById(field.id)
    app.save(collection)
  } catch (e) { /* ignore */ }
})
