/// <reference path="../pb_data/types.d.ts" />
// Drop the `weight` field from tasks + archived_tasks.
//
// Plan progress no longer uses per-task weights — recalcPlanProgress in
// helpers.js computes a simple average of task progress instead (the field was
// an estimate that added maintenance cost across the UI, exports and KPI pages).
//
// Existing deployments get the field removed on next boot; fresh instances get
// the schema from web/scripts/bootstrap-schema.mjs (which no longer creates it).
migrate((app) => {
  const dropField = (collectionName, fieldName) => {
    try {
      const collection = app.findCollectionByNameOrId(collectionName)
      let field = null
      for (let i = 0; i < collection.fields.length; i++) {
        if (collection.fields[i].name === fieldName) { field = collection.fields[i]; break }
      }
      if (field) {
        collection.fields.removeById(field.id)
        app.save(collection)
        console.log(`  removed ${collectionName}.${fieldName}`)
      }
    } catch (e) {
      console.log(`  skip ${collectionName}.${fieldName}: ${e.message}`)
    }
  }
  dropField("tasks", "weight")
  dropField("archived_tasks", "weight")
}, (app) => {
  // best-effort revert (field ids are regenerated by PB)
  const addField = (collectionName) => {
    try {
      const collection = app.findCollectionByNameOrId(collectionName)
      let exists = false
      for (let i = 0; i < collection.fields.length; i++) {
        if (collection.fields[i].name === "weight") { exists = true; break }
      }
      if (!exists) {
        collection.fields.add({ name: "weight", type: "number", required: false, min: null, max: null })
        app.save(collection)
      }
    } catch (e) {
      console.log(`  revert skip ${collectionName}: ${e.message}`)
    }
  }
  addField("tasks")
  addField("archived_tasks")
})
